import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import { Inter } from 'next/font/google';
import AuthProvider from '@/provider/AuthProvider';
import ReactQueryProvider from '@/provider/ReactQueryProvider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Tracer',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <NextTopLoader color='#4f46e5' />
                <ReactQueryProvider>
                    <AuthProvider>{children}</AuthProvider>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
